### ISSUE TITLE
Feeding default pet doesn't seem to work

### ISSUE THREAD

**Issue by fleure** [fleure/kentpet#6]
10:26 < catboy> !defaultpet 1
10:26 < kentpet> catboy: Default pet set.
10:26 < catboy> !feed feast
10:26 < catboy> !feed 1 feast
10:26 < kentpet> catboy: You fed your pet. They are now hungry

**Comment by fleure** [comment]
Traceback:

Traceback (most recent call last):
  File "./kentpet.py", line 104, in do_cmd
    message = getattr(self.modules[module], arg[0])(arg[1:], nick, private)
  File "/root/code/kentpet/modules/pets.py", line 313, in feed
    amount_string = arg[1].lower()
IndexError: list index out of range
